title: Desarrollo de Aplicaciones
description: Material del curso

theme: just-the-docs

url: https://mariomurc.github.io

aux_links:
  "Repositorio":
    - "https://github.com/mariomurc/ProgramacionMultiMediaYDispositivosMoviles"
